### ISSUE TITLE
Small corner radius on top left corner of completion banner

### ISSUE THREAD

**Issue by jpaas** [danielniemeyer/DNTutorial#3]
I'm not sure if its a design element or a mistake, but the top left corner of the blue completion banner has a radiused corner.

**Comment by danielniemeyer** [comment]
Yeah, it was a design decision at the time, but I agree that it looks like a mistake, Ill fix it soon, thanks for commenting on it ;)

**Comment by danielniemeyer** [comment]
Fixed in 0.1.4
